### ISSUE TITLE
remove debugging `print()` statements

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/canvas-lti-redirect-tool#12]
[`backend/settings.py`](https://github.com/tl-its-umich-edu/canvas-lti-redirect-tool/blob/cd8aae5deba3706a5a4e2b28d2757e5e4c642dda/backend/settings.py) contains `print()` statements, probably for debugging.  These display every time the file is imported, which means multiple times when the application is running, whenever `manage.py` is called, etc.

These should be removed or changed to logging statements which use the `DEBUG` facility.

**Comment by pushyamig** [comment]
I am address it in this PR https://github.com/tl-its-umich-edu/canvas-lti-redirect-tool/pull/10/files
